name: Remove test container image
on:
  pull_request:
    types: [closed]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  remove-test-image:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TODO"
